# Generated by Django 5.1 on 2025-03-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_type', models.CharField(choices=[('CALL', 'Phone Call'), ('VISIT', 'Field Visit'), ('SMS', 'SMS Reminder'), ('EMAIL', 'Email Reminder'), ('OTHER', 'Other')], max_length=20, verbose_name='follow-up type')),
                ('scheduled_date', models.DateField(verbose_name='scheduled date')),
                ('scheduled_time', models.TimeField(blank=True, null=True, verbose_name='scheduled time')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10, verbose_name='priority')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('RESCHEDULED', 'Rescheduled'), ('CANCELED', 'Canceled')], default='PENDING', max_length=20, verbose_name='status')),
                ('result', models.TextField(blank=True, verbose_name='result')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'follow-up',
                'verbose_name_plural': 'follow-ups',
                'ordering': ['status', 'scheduled_date', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('CALL', 'Phone Call'), ('MEETING', 'In-Person Meeting'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('VISIT', 'Field Visit'), ('OTHER', 'Other')], max_length=20, verbose_name='interaction type')),
                ('contact_number', models.CharField(blank=True, max_length=15, verbose_name='contact number')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='contact person')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='end time')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='duration (seconds)')),
                ('outcome', models.CharField(blank=True, choices=[('PAYMENT_PROMISED', 'Payment Promised'), ('PAYMENT_MADE', 'Payment Made'), ('NO_ANSWER', 'No Answer'), ('WRONG_NUMBER', 'Wrong Number'), ('NUMBER_DISCONNECTED', 'Number Disconnected'), ('CUSTOMER_UNAVAILABLE', 'Customer Unavailable'), ('DISPUTED', 'Disputed'), ('REFUSED_TO_PAY', 'Refused to Pay'), ('OTHER', 'Other')], max_length=30, null=True, verbose_name='outcome')),
                ('notes', models.TextField(verbose_name='notes')),
                ('payment_promise_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='payment promise amount')),
                ('payment_promise_date', models.DateField(blank=True, null=True, verbose_name='payment promise date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'interaction',
                'verbose_name_plural': 'interactions',
                'ordering': ['-start_time'],
            },
        ),
    ]
