# Generated by Django 5.1 on 2025-04-06 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        ('interactions', '0001_initial'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_follow_ups', to=settings.AUTH_USER_MODEL, verbose_name='assigned to'),
        ),
        migrations.AddField(
            model_name='followup',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_follow_ups', to=settings.AUTH_USER_MODEL, verbose_name='completed by'),
        ),
        migrations.AddField(
            model_name='followup',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_follow_ups', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='followup',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='customers.customer', verbose_name='customer'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='customers.customer', verbose_name='customer'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='initiated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_interactions', to=settings.AUTH_USER_MODEL, verbose_name='initiated by'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='loans.loan', verbose_name='loan'),
        ),
        migrations.AddField(
            model_name='followup',
            name='interaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='interactions.interaction', verbose_name='interaction'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['customer'], name='interaction_custome_a64fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['loan'], name='interaction_loan_id_52fd43_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['initiated_by'], name='interaction_initiat_453a9b_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['start_time'], name='interaction_start_t_81e69e_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['customer'], name='interaction_custome_ccfbc5_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['assigned_to'], name='interaction_assigne_1dfb53_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['status'], name='interaction_status_2e0545_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['scheduled_date'], name='interaction_schedul_7c92d2_idx'),
        ),
    ]
