# Generated by Django 5.1 on 2025-03-27 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinteraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attachment',
            name='interaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='interactions.customerinteraction'),
        ),
        migrations.AddField(
            model_name='customerinteraction',
            name='disposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to='interactions.disposition'),
        ),
    ]
