# Generated by Django 5.1 on 2025-03-27 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_initial'),
    ]

    operations = [
    ]
