# Generated by Django 5.1 on 2025-03-29 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customerassignment_unique_together_and_more'),
        ('interactions', '0003_auto_20250327_2330'),
        ('loans', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinteraction',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerinteraction',
            name='disposition',
        ),
        migrations.RemoveField(
            model_name='customerinteraction',
            name='user',
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('CALL', 'Phone Call'), ('MEETING', 'In-Person Meeting'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('VISIT', 'Field Visit'), ('OTHER', 'Other')], max_length=20, verbose_name='interaction type')),
                ('contact_number', models.CharField(blank=True, max_length=15, verbose_name='contact number')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='contact person')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='end time')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='duration (seconds)')),
                ('outcome', models.CharField(blank=True, choices=[('PAYMENT_PROMISED', 'Payment Promised'), ('PAYMENT_MADE', 'Payment Made'), ('NO_ANSWER', 'No Answer'), ('WRONG_NUMBER', 'Wrong Number'), ('NUMBER_DISCONNECTED', 'Number Disconnected'), ('CUSTOMER_UNAVAILABLE', 'Customer Unavailable'), ('DISPUTED', 'Disputed'), ('REFUSED_TO_PAY', 'Refused to Pay'), ('OTHER', 'Other')], max_length=30, null=True, verbose_name='outcome')),
                ('notes', models.TextField(verbose_name='notes')),
                ('payment_promise_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='payment promise amount')),
                ('payment_promise_date', models.DateField(blank=True, null=True, verbose_name='payment promise date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='customers.customer', verbose_name='customer')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_interactions', to=settings.AUTH_USER_MODEL, verbose_name='initiated by')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='loans.loan', verbose_name='loan')),
            ],
            options={
                'verbose_name': 'interaction',
                'verbose_name_plural': 'interactions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_type', models.CharField(choices=[('CALL', 'Phone Call'), ('VISIT', 'Field Visit'), ('SMS', 'SMS Reminder'), ('EMAIL', 'Email Reminder'), ('OTHER', 'Other')], max_length=20, verbose_name='follow-up type')),
                ('scheduled_date', models.DateField(verbose_name='scheduled date')),
                ('scheduled_time', models.TimeField(blank=True, null=True, verbose_name='scheduled time')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10, verbose_name='priority')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('RESCHEDULED', 'Rescheduled'), ('CANCELED', 'Canceled')], default='PENDING', max_length=20, verbose_name='status')),
                ('result', models.TextField(blank=True, verbose_name='result')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_follow_ups', to=settings.AUTH_USER_MODEL, verbose_name='assigned to')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_follow_ups', to=settings.AUTH_USER_MODEL, verbose_name='completed by')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_follow_ups', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='customers.customer', verbose_name='customer')),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='interactions.interaction', verbose_name='interaction')),
            ],
            options={
                'verbose_name': 'follow-up',
                'verbose_name_plural': 'follow-ups',
                'ordering': ['status', 'scheduled_date', 'scheduled_time'],
            },
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='Disposition',
        ),
        migrations.DeleteModel(
            name='CustomerInteraction',
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['customer'], name='interaction_custome_a64fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['loan'], name='interaction_loan_id_52fd43_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['initiated_by'], name='interaction_initiat_453a9b_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['start_time'], name='interaction_start_t_81e69e_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['customer'], name='interaction_custome_ccfbc5_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['assigned_to'], name='interaction_assigne_1dfb53_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['status'], name='interaction_status_2e0545_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['scheduled_date'], name='interaction_schedul_7c92d2_idx'),
        ),
    ]
