# Generated by Django 5.1 on 2025-03-27 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerassignment',
            name='collection_officer',
            field=models.ForeignKey(limit_choices_to={'role': 'COLLECTION_OFFICER'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerassignment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='loan',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='customers.customer'),
        ),
        migrations.AlterUniqueTogether(
            name='customerassignment',
            unique_together={('customer', 'collection_officer', 'status')},
        ),
    ]
