# Generated by Django 5.1 on 2025-03-29 09:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customerassignment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='customerassignment',
            name='collection_officer',
        ),
        migrations.RemoveField(
            model_name='customerassignment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='customer',
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'customer', 'verbose_name_plural': 'customers'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id_proof_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id_proof_type',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='status',
        ),
        migrations.AddField(
            model_name='customer',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'COLLECTION_OFFICER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='customer',
            name='employer',
            field=models.CharField(blank=True, max_length=255, verbose_name='employer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='', max_length=50, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=10, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='customer',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='job title'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='', max_length=50, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='monthly income'),
        ),
        migrations.AddField(
            model_name='customer',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='national ID'),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='postal code'),
        ),
        migrations.AddField(
            model_name='customer',
            name='primary_phone',
            field=models.CharField(default='', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='primary phone'),
        ),
        migrations.AddField(
            model_name='customer',
            name='risk_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='risk score'),
        ),
        migrations.AddField(
            model_name='customer',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='secondary phone'),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='state/province'),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='email address'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['primary_phone'], name='customers_c_primary_c976f4_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['national_id'], name='customers_c_nationa_10c874_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_name', 'first_name'], name='customers_c_last_na_27dbcc_idx'),
        ),
        migrations.DeleteModel(
            name='CustomerAssignment',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
