# Generated by Django 5.1 on 2025-03-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20250329_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.CharField(blank=True, max_length=100, verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='customer',
            name='emi_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('NOT_PAID', 'Not Paid')], default='NOT_PAID', max_length=10, verbose_name='EMI status'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer Not to Say')], default='PREFER_NOT_TO_SAY', max_length=20, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='national ID'),
        ),
    ]
