# Generated by Django 5.1 on 2025-03-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_branch_customer_emi_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='emi_status',
        ),
        migrations.AddField(
            model_name='customer',
            name='paid_status',
            field=models.BooleanField(default=False, help_text='Whether the customer has paid their EMI', verbose_name='paid status'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=10, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='national ID'),
        ),
    ]
