# Generated by Django 5.1 on 2025-03-30 15:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_reference', models.CharField(max_length=20, unique=True, verbose_name='loan reference')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('PAID', 'Paid'), ('DEFAULTED', 'Defaulted'), ('RESTRUCTURED', 'Restructured'), ('WRITTEN_OFF', 'Written Off')], default='PENDING', max_length=20, verbose_name='status')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='principal amount')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='interest rate (%)')),
                ('application_date', models.DateField(auto_now_add=True, verbose_name='application date')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='approval date')),
                ('disbursement_date', models.DateField(blank=True, null=True, verbose_name='disbursement date')),
                ('first_payment_date', models.DateField(blank=True, null=True, verbose_name='first payment date')),
                ('maturity_date', models.DateField(blank=True, null=True, verbose_name='maturity date')),
                ('term_months', models.PositiveIntegerField(verbose_name='term (months)')),
                ('payment_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], default='MONTHLY', max_length=20, verbose_name='payment frequency')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='amount paid')),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name='last payment date')),
                ('days_past_due', models.PositiveIntegerField(default=0, verbose_name='days past due')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'loan',
                'verbose_name_plural': 'loans',
                'ordering': ['-application_date'],
                'permissions': [('approve_loan', 'Can approve loans'), ('disburse_loan', 'Can disburse loans'), ('restructure_loan', 'Can restructure loans'), ('write_off_loan', 'Can write off loans')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reference', models.CharField(max_length=30, unique=True, verbose_name='payment reference')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='amount')),
                ('payment_date', models.DateField(verbose_name='payment date')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], default='CASH', max_length=20, verbose_name='payment method')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
