# Generated by Django 5.1 on 2025-03-30 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['COLLECTION_OFFICER', 'MANAGER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='customers.customer', verbose_name='customer'),
        ),
        migrations.AddField(
            model_name='loan',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loan', verbose_name='loan'),
        ),
        migrations.AddField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL, verbose_name='received by'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['loan_reference'], name='loans_loan_loan_re_e36631_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status'], name='loans_loan_status_962e99_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['customer'], name='loans_loan_custome_53a43c_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['assigned_officer'], name='loans_loan_assigne_adfbd8_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_reference'], name='loans_payme_payment_f265ef_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['loan'], name='loans_payme_loan_id_35d8fe_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='loans_payme_payment_7579c7_idx'),
        ),
    ]
